load_module modules/ngx_http_acme_module.so;

user nginx nginx;
worker_processes auto;
worker_rlimit_nofile 2048;

pid       /run/nginx.pid;
error_log /var/log/nginx/error.log notice;

events {
	worker_connections 1024;
}

http {
	include      /etc/nginx/mime.types;
	default_type application/octet-stream;

	log_format main '$remote_addr - $remote_user [$time_local] "$request" '
					'$status $body_bytes_sent "$http_referer" '
					'"$http_user_agent" "$http_x_forwarded_for"';

	access_log /var/log/nginx/access.log main;

	sendfile on;
	gzip on;
	keepalive_timeout 10;
	server_tokens off;

	resolver 1.1.1.1;

	### For ssl cert
	acme_issuer letsencrypt {
		uri			https://acme-v02.api.letsencrypt.org/directory;
		# contact	admin@example.test;
		state_path	/var/cache/nginx/acme-letsencrypt;

		accept_terms_of_service;
	}

	### General listener on port 80 is required to process ACME HTTP-01 challenges
	server {
		listen 80 default_server;
		listen [::]:80 default_server;

		### Redirect to https
		return 301 https://$host$request_uri;
	}

	server {
		listen 443 ssl;
		listen [::]:443 ssl;

		server_name id.fribyte.no;

		### SSL
		acme_certificate      letsencrypt;
		ssl_certificate       $acme_certificate;
		ssl_certificate_key   $acme_certificate_key;
		ssl_certificate_cache max=2;

		location / {
			proxy_pass https://localhost:8443;
			proxy_http_version 1.1;
			proxy_set_header Host $server_name;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}
}