---
- name: Common server roles
  hosts: all
  roles:
    - common
    - role: community.beszel.agent
      vars:
        agent_public_key: "{{ beszel_agent_public_key }}"
        agent_token: "{{ beszel_agent_token }}"
        agent_hub_url: "{{ beszel_agent_hub_url }}"
  become: true

- name: Kanidm host config
  hosts: kanidm
  pre_tasks:
    - name: Install nginx
      ansible.builtin.include_role:
        name: nginxinc.nginx
  roles:
    - kanidm
  become: true
